2.5 networking frontend
JamesPartsafas/soen390 pull request #78
Opened 2023-02-09 15:35 UTC by CHADBUCK13

Added network frontend and fixed navbar/footer. Made small refactor to make isUserAuthenticated easier to use. Added network page to controller.

This PR closes #70

2023-02-09 16:13 UTC, JamesPartsafas approved these changes

2023-02-09 16:13 UTC, JamesPartsafas commented on synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
> +    public static boolean isUserAuthenticated() {
This is a good change.

2023-02-10 02:40 UTC, janong24 requested changes
Please remove the suggested section as discussed, thanks!

2023-02-10 02:40 UTC, janong24 commented on synapsis/src/main/resources/templates/pages/network.html
> +        </div>
Please remove the suggested section as discussed. Thanks!

2023-02-11 16:29 UTC, janong24 approved these changes

2023-02-11 16:29 UTC, janong24 commented
All changes have been made. PR good to merge.

2023-02-11 16:33 UTC, merged