68 homepage design
JamesPartsafas/soen390 pull request #87
Opened 2023-02-12 21:09 UTC by janong24

Homepage design complete.
Graphical assets uploaded.

Closes #68

2023-02-13 02:04 UTC, kennyphan100 commented
Could you possibly take a screenshot of the homepage and post it in the description of the PR, just so that we can see what we are working with. If you are busy, then don't worry about it.

2023-02-13 03:30 UTC, janong24 commented
@kennyphan100 Yeah, for sure. It's an exact replica of the Figma.

https://drive.google.com/file/d/1jvQ-LMVo0lPDRqUbh-pMTJZWlYTq8vFv/view?usp=share_link

2023-02-13 03:44 UTC, kennyphan100 commented
> @kennyphan100 Yeah, for sure. It's an exact replica of the Figma.
> 
> https://drive.google.com/file/d/1jvQ-LMVo0lPDRqUbh-pMTJZWlYTq8vFv/view?usp=share_link

It looks amazing, well done!

2023-02-13 20:19 UTC, CHADBUCK13 requested changes
Looks good! I have a feeling you may not merged the main branch into your branch before comitting though, please see the comments.

2023-02-13 22:04 UTC, janong24 commented on synapsis/src/main/resources/templates/fragments/navbar.html
>      </nav>
Thanks for pointing these out! I think these changes came after my PR. I'll resolve these and resend a request.

2023-02-13 22:20 UTC, janong24 commented on synapsis/src/main/resources/templates/fragments/navbar.html
>      </nav>
I've made the necessary changes. Please take a look when you have the time @CHADBUCK13. Thanks!

2023-02-14 18:49 UTC, Chr728 approved these changes

2023-02-16 02:08 UTC, CHADBUCK13 approved these changes

2023-02-16 02:08 UTC, merged